### ISSUE TITLE
initClass runs too soon?

### ISSUE THREAD

**Issue by jgresh** [musikinformatik/AudacityLabels#1]
Thanks for this quark, it's useful. I'd written a primitive version of it but yours is more fully featured. I do have a question.

When I try to play the example or my own variation that depends on the synths you add in initClass (e.g. \labelPlayer_1) it doesn't find the synth. I think  this is because initClass runs once when the interpreter boots but the server isn't running yet. Is there a systematic way around this? My current workarounds are either to recompile the class library after the server is booted or to just run the synthdefs interactively when I need them. If this truly is a "bug" and there's no better way, maybe just create a class method to init the test synths, and then you can remove the whole initClass method.

Thanks again! -Jason

**Comment by telephon** [comment]
Great that it is useful. If you have any suggestions for improvement, let me know.

>When I try to play the example or my own variation that depends on the synths you add in initClass (e.g. \labelPlayer_1) it doesn't find the synth.

Normally, the `SynthDescLib` should send all the added `SynthDef`s to the server each time it boots. Can you take a look if this happens?

```supercollider
(
SynthDef(\dummy64, { }).add;

s.reboot {
	(instrument: \dummy64).play;
}
)

```

It should find the `\dummy64` synth def.

Btw. if you make your own SynthDef, you can put its name into the events of the dictionary and it'll just use that instead. Maybe I should allow to pass a custom event to the `read` message to make this explicit.

**Comment by avdrd** [comment]
I'm not seeing the bug that Jason reported at the moment, but in general it has been suggested by James Harkins on the forum that `StartUp` is the more proper point at which to add new synths.

One issue with initClass is that currentEnvironment is nil during the initClass phase. It only gets instantiated thereafter, so it is available in StartUp.run. However I'm not seeing that issue affecting AudacityLabels itself, directly. For me it was an issue because I had modified the SynthDef builder to look at some environment variables and my hack was failing for the synths that AudacityLabels instantiates. I don't know of any other quarks that might do something like what my hack was doing, so I have no idea what interaction Jason is seeing, but it's perhaps something like that.

**Comment by telephon** [comment]
@jgresh let me knoww if this is still a problem …
